/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.macpod.srv1console;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int dark_green=0x7f050000;
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int picview=0x7f060004;
        public static final int server_field=0x7f060001;
        public static final int server_label=0x7f060000;
        public static final int state_button=0x7f060003;
        public static final int status_label=0x7f060002;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int default_server=0x7f040006;
        public static final int server_name=0x7f040000;
        public static final int state_start=0x7f040003;
        public static final int state_stop=0x7f040002;
        public static final int status_running=0x7f040005;
        public static final int status_stopped=0x7f040004;
    }
}
